In [20]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
pd.set_option('display.max_rows',None)

In [21]:
df = pd.read_csv("/content/Iris.csv")

In [22]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
16,17,5.4,3.9,1.3,0.4,Iris-setosa
17,18,5.1,3.5,1.4,0.3,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
19,20,5.1,3.8,1.5,0.3,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
21,22,5.1,3.7,1.5,0.4,Iris-setosa
22,23,4.6,3.6,1.0,0.2,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
31,32,5.4,3.4,1.5,0.4,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
35,36,5.0,3.2,1.2,0.2,Iris-setosa
36,37,5.5,3.5,1.3,0.2,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
39,40,5.1,3.4,1.5,0.2,Iris-setosa
40,41,5.0,3.5,1.3,0.3,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
43,44,5.0,3.5,1.6,0.6,Iris-setosa
44,45,5.1,3.8,1.9,0.4,Iris-setosa
45,46,4.8,3.0,1.4,0.3,Iris-setosa
46,47,5.1,3.8,1.6,0.2,Iris-setosa
47,48,4.6,3.2,1.4,0.2,Iris-setosa
48,49,5.3,3.7,1.5,0.2,Iris-setosa
49,50,5.0,3.3,1.4,0.2,Iris-setosa
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
58,59,6.6,2.9,4.6,1.3,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
67,68,5.8,2.7,4.1,1.0,Iris-versicolor
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
69,70,5.6,2.5,3.9,1.1,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
71,72,6.1,2.8,4.0,1.3,Iris-versicolor
72,73,6.3,2.5,4.9,1.5,Iris-versicolor
73,74,6.1,2.8,4.7,1.2,Iris-versicolor
74,75,6.4,2.9,4.3,1.3,Iris-versicolor
75,76,6.6,3.0,4.4,1.4,Iris-versicolor
76,77,6.8,2.8,4.8,1.4,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
79,80,5.7,2.6,3.5,1.0,Iris-versicolor
80,81,5.5,2.4,3.8,1.1,Iris-versicolor
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
82,83,5.8,2.7,3.9,1.2,Iris-versicolor
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor
89,90,5.5,2.5,4.0,1.3,Iris-versicolor
90,91,5.5,2.6,4.4,1.2,Iris-versicolor
91,92,6.1,3.0,4.6,1.4,Iris-versicolor
92,93,5.8,2.6,4.0,1.2,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
94,95,5.6,2.7,4.2,1.3,Iris-versicolor
95,96,5.7,3.0,4.2,1.2,Iris-versicolor
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
97,98,6.2,2.9,4.3,1.3,Iris-versicolor
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
99,100,5.7,2.8,4.1,1.3,Iris-versicolor
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [24]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [25]:
df.shape

(150, 6)

In [26]:
LE = LabelEncoder()

In [27]:
df['Species'] = LE.fit_transform(df['Species'])

In [29]:
df

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
5      6            5.4           3.9            1.7           0.4        0
6      7            4.6           3.4            1.4           0.3        0
7      8            5.0           3.4            1.5           0.2        0
8      9            4.4           2.9            1.4           0.2        0
9     10            4.9           3.1            1.5           0.1        0
10    11            5.4           3.7            1.5           0.2        0
11    12            4.8           3.4            1.6           0.2        0
12    13            4.8           3.0            1.4           0.1        0
13    14            4.3           3.0            1.1           0.1        0
14    15            5.8           4.0            1.2           0.2        0
15    16            5.7           4.4            1.5           0.4        0
16    17            5.4           3.9            1.3           0.4        0
17    18            5.1           3.5            1.4           0.3        0
18    19            5.7           3.8            1.7           0.3        0
19    20            5.1           3.8            1.5           0.3        0
20    21            5.4           3.4            1.7           0.2        0
21    22            5.1           3.7            1.5           0.4        0
22    23            4.6           3.6            1.0           0.2        0
23    24            5.1           3.3            1.7           0.5        0
24    25            4.8           3.4            1.9           0.2        0
25    26            5.0           3.0            1.6           0.2        0
26    27            5.0           3.4            1.6           0.4        0
27    28            5.2           3.5            1.5           0.2        0
28    29            5.2           3.4            1.4           0.2        0
29    30            4.7           3.2            1.6           0.2        0
30    31            4.8           3.1            1.6           0.2        0
31    32            5.4           3.4            1.5           0.4        0
32    33            5.2           4.1            1.5           0.1        0
33    34            5.5           4.2            1.4           0.2        0
34    35            4.9           3.1            1.5           0.1        0
35    36            5.0           3.2            1.2           0.2        0
36    37            5.5           3.5            1.3           0.2        0
37    38            4.9           3.1            1.5           0.1        0
38    39            4.4           3.0            1.3           0.2        0
39    40            5.1           3.4            1.5           0.2        0
40    41            5.0           3.5            1.3           0.3        0
41    42            4.5           2.3            1.3           0.3        0
42    43            4.4           3.2            1.3           0.2        0
43    44            5.0           3.5            1.6           0.6        0
44    45            5.1           3.8            1.9           0.4        0
45    46            4.8           3.0            1.4           0.3        0
46    47            5.1           3.8            1.6           0.2        0
47    48            4.6           3.2            1.4           0.2        0
48    49            5.3           3.7            1.5           0.2        0
49    50            5.0           3.3            1.4           0.2        0
50    51            7.0           3.2            4.7           1.4        1
51    52            6.4           3.2            4.5           1.5        1
52    53            6.9           3.1            4.9           1.5        1
53    54            5.5           2.3            4.0           1.3        1
54    55            6.5           2.8            4.6           1.5        1
55    56            5.7           2.8            4.5           1.3        1
56    57            6.3           3.3            4.7           1.6        1
57    58            4.9           2.4            3.3           1.0        1
58    59            6.6           2.9            4.6           1.3        1
59    60            5.2           2.7            3.9           1.4        1
60    61            5.0           2.0            3.5           1.0        1
61    62            5.9           3.0            4.2           1.5        1
62    63            6.0           2.2            4.0           1.0        1
63    64            6.1           2.9            4.7           1.4        1
64    65            5.6           2.9            3.6           1.3        1
65    66            6.7           3.1            4.4           1.4        1
66    67            5.6           3.0            4.5           1.5        1
67    68            5.8           2.7            4.1           1.0        1
68    69            6.2           2.2            4.5           1.5        1
69    70            5.6           2.5            3.9           1.1        1
70    71            5.9           3.2            4.8           1.8        1
71    72            6.1           2.8            4.0           1.3        1
72    73            6.3           2.5            4.9           1.5        1
73    74            6.1           2.8            4.7           1.2        1
74    75            6.4           2.9            4.3           1.3        1
75    76            6.6           3.0            4.4           1.4        1
76    77            6.8           2.8            4.8           1.4        1
77    78            6.7           3.0            5.0           1.7        1
78    79            6.0           2.9            4.5           1.5        1
79    80            5.7           2.6            3.5           1.0        1
80    81            5.5           2.4            3.8           1.1        1
81    82            5.5           2.4            3.7           1.0        1
82    83            5.8           2.7            3.9           1.2        1
83    84            6.0           2.7            5.1           1.6        1
84    85            5.4           3.0            4.5           1.5        1
85    86            6.0           3.4            4.5           1.6        1
86    87            6.7           3.1            4.7           1.5        1
87    88            6.3           2.3            4.4           1.3        1
88    89            5.6           3.0            4.1           1.3        1
89    90            5.5           2.5            4.0           1.3        1
90    91            5.5           2.6            4.4           1.2        1
91    92            6.1           3.0            4.6           1.4        1
92    93            5.8           2.6            4.0           1.2        1
93    94            5.0           2.3            3.3           1.0        1
94    95            5.6           2.7            4.2           1.3        1
95    96            5.7           3.0            4.2           1.2        1
96    97            5.7           2.9            4.2           1.3        1
97    98            6.2           2.9            4.3           1.3        1
98    99            5.1           2.5            3.0           1.1        1
99   100            5.7           2.8            4.1           1.3        1
100  101            6.3           3.3            6.0           2.5        2
101  102            5.8           2.7            5.1           1.9        2
102  103            7.1           3.0            5.9           2.1        2
103  104            6.3           2.9            5.6           1.8        2
104  105            6.5           3.0            5.8           2.2        2
105  106            7.6           3.0            6.6           2.1        2
106  107            4.9           2.5            4.5           1.7        2
107  108            7.3           2.9            6.3           1.8        2
108  109            6.7           2.5            5.8           1.8        2
109  110            7.2           3.6            6.1           2.5        2
110  111            6.5           3.2            5.1           2.0        2
111  112            6.4           2.7            5.3           1.9        2
112  113            6.8           3.0            5.5           2.1        2
113  114            5.7           2.5            5.0           2.0        2
114  115            5.8           2.8            5.1           2.4        2
115  116            6.4           3.2            5.3           2.3        2
116  117            6.5           3.0            5.5           1.8        2
117  118            7.7           3.8            6.7           2.2        2
118  119            7.7           2.6            6.9           2.3        2
119  120            6.0           2.2            5.0           1.5        2
120  121            6.9           3.2            5.7           2.3        2
121  122            5.6           2.8            4.9           2.0        2
122  123            7.7           2.8            6.7           2.0        2
123  124            6.3           2.7            4.9           1.8        2
124  125            6.7           3.3            5.7           2.1        2
125  126            7.2           3.2            6.0           1.8        2
126  127            6.2           2.8            4.8           1.8        2
127  128            6.1           3.0            4.9           1.8        2
128  129            6.4           2.8            5.6           2.1        2
129  130            7.2           3.0            5.8           1.6        2
130  131            7.4           2.8            6.1           1.9        2
131  132            7.9           3.8            6.4           2.0        2
132  133            6.4           2.8            5.6           2.2        2
133  134            6.3           2.8            5.1           1.5        2
134  135            6.1           2.6            5.6           1.4        2
135  136            7.7           3.0            6.1           2.3        2
136  137            6.3           3.4            5.6           2.4        2
137  138            6.4           3.1            5.5           1.8        2
138  139            6.0           3.0            4.8           1.8        2
139  140            6.9           3.1            5.4           2.1        2
140  141            6.7           3.1            5.6           2.4        2
141  142            6.9           3.1            5.1           2.3        2
142  143            5.8           2.7            5.1           1.9        2
143  144            6.8           3.2            5.9           2.3        2
144  145            6.7           3.3            5.7           2.5        2
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

In [30]:
X = df.drop(columns = 'Species',axis = 1)
Y = df['Species']

In [31]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42,stratify=Y)

In [32]:
model = LogisticRegression()

In [34]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [35]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)
print("Accuracy Score of X_train:",training_data_accuracy)

Accuracy Score of X_train: 1.0

In [36]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)
print("Accuracy Score of X_test:",test_data_accuracy)

Accuracy Score of X_test: 1.0

In [45]:
input = (95,5.6,2.7,4.2,1.3)

In [46]:
numpy = np.asarray(input)

In [47]:
reshape = numpy.reshape(1,-1)

In [48]:
prediction = model.predict(reshape)
if prediction == 0:
  print("Iris-setosa")
elif prediction == 1:
  print("Iris-versicolor")
else:
  print("Iris-virginica")

Iris-versicolor

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(