In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv("/content/Class_BanknoteAuth.csv")

In [9]:
df.head(30)

        Var     Skew     Kurt  Entropy  Class
0   3.62160   8.6661 -2.80730 -0.44699      0
1   4.54590   8.1674 -2.45860 -1.46210      0
2   3.86600  -2.6383  1.92420  0.10645      0
3   3.45660   9.5228 -4.01120 -3.59440      0
4   0.32924  -4.4552  4.57180 -0.98880      0
5   4.36840   9.6718 -3.96060 -3.16250      0
6   3.59120   3.0129  0.72888  0.56421      0
7   2.09220  -6.8100  8.46360 -0.60216      0
8   3.20320   5.7588 -0.75345 -0.61251      0
9   1.53560   9.1772 -2.27180 -0.73535      0
10  1.22470   8.7779 -2.21350 -0.80647      0
11  3.98990  -2.7066  2.39460  0.86291      0
12  1.89930   7.6625  0.15394 -3.11080      0
13 -1.57680  10.8430  2.54620 -2.93620      0
14  3.40400   8.7261 -2.99150 -0.57242      0
15  4.67650  -3.3895  3.48960  1.47710      0
16  2.67190   3.0646  0.37158  0.58619      0
17  0.80355   2.8473  4.34390  0.60170      0
18  1.44790  -4.8794  8.34280 -2.10860      0
19  5.24230  11.0272 -4.35300 -4.10130      0
20  5.78670   7.8902 -2.61960 -0.48708      0
21  0.32920  -4.4552  4.57180 -0.98880      0
22  3.93620  10.1622 -3.82350 -4.01720      0
23  0.93584   8.8855 -1.68310 -1.65990      0
24  4.43380   9.8870 -4.67950 -3.74830      0
25  0.70570  -5.4981  8.33680 -2.87150      0
26  1.14320  -3.7413  5.57770 -0.63578      0
27 -0.38214   8.3909  2.16240 -3.74050      0
28  6.56330   9.8187 -4.41130 -3.22580      0
29  4.89060  -3.3584  3.42020  1.09050      0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Var      1372 non-null   float64
 1   Skew     1372 non-null   float64
 2   Kurt     1372 non-null   float64
 3   Entropy  1372 non-null   float64
 4   Class    1372 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB

In [6]:
df.describe()

               Var         Skew         Kurt      Entropy        Class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922350     1.397627    -1.191657     0.444606
std       2.842763     5.869043     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [7]:
df.shape

(1372, 5)

In [8]:
df.isnull().sum()

Var        0
Skew       0
Kurt       0
Entropy    0
Class      0
dtype: int64

In [10]:
df.tail()

          Var      Skew     Kurt  Entropy  Class
1367  0.40614   1.34920  -1.4501 -0.55949      1
1368 -1.38870  -4.87730   6.4774  0.34179      1
1369 -3.75030 -13.45860  17.5932 -2.77710      1
1370 -3.56370  -8.38270  12.3930 -1.28230      1
1371 -2.54190  -0.65804   2.6842  1.19520      1

In [11]:
df['Class'].value_counts()

Class
0    762
1    610
Name: count, dtype: int64

In [14]:
X = df.drop('Class',axis=1)
Y = df['Class']

In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [16]:
model = LogisticRegression()

In [17]:
model.fit(X_train,Y_train)

LogisticRegression()

In [18]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)
print("Training Dataa Accuracy:",training_data_accuracy)

Training Dataa Accuracy: 0.9927073837739289

In [19]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)
print("Testing data Accuracy:",test_data_accuracy)

Testing data Accuracy: 0.9854545454545455

In [25]:
input = (1.44790,-4.8794,8.34280,-2.10860)

In [26]:
numpy = np.asarray(input)

In [27]:
reshape = numpy.reshape(1,-1)

In [28]:
prediction = model.predict(reshape)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [29]:
if prediction == 0:
  print("You're Authored")
else:
  print("You're not Authored")

You're Authored